SOUNDCLOUD/SOUNDCLOUD/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('register.urls')),
    path('my_audio/', include('myaudio.urls', namespace='myaudio')),
    path('', include('main.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls))
                  ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SOUNDCLOUD/main/urls.py
from django.urls import path
from .views import *

app_name = 'main'
urlpatterns = [
    path('', MusicHome.as_view(), name='home'),
    path('add/', AddMusic.as_view(), name='add'),
    path('category/<slug:cat_slug>/', ListCategories.as_view(), name='category')
]

SOUNDCLOUD/register/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, \
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path
from .views import *

app_name = 'register'
urlpatterns = [
    path('', LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password-change/', UserChangePassword.as_view(), name='password_change'),
    path('password-reset/', PasswordResetView.as_view(
        template_name='register/password_reset_form.html',
        email_template_name='register/password_reset_email.html',
        success_url=reverse_lazy('register:password_reset_done')),
         name='password_reset'),
    path('password-reset-done/', PasswordResetDoneView.as_view(
        template_name='register/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='register/password_reset_confirm.html',
        success_url=reverse_lazy('register:login')),
         name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(
        template_name='register/password_reset_complete.html'),
         name='password_reset_complete'),
    path('register/', RegisterUser.as_view(), name='reg'),
    path('profile/', Profile.as_view(), name='profile'),
]

SOUNDCLOUD/register/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    image = models.ImageField(upload_to='users', blank=True, null=True, verbose_name='Фотография')
    day_birth = models.DateTimeField(blank=True, null=True, verbose_name='День рождения')

SOUNDCLOUD/register/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.contrib.auth.models import User
from django import forms


class RegisterUser(UserCreationForm):
    username = forms.CharField(label='Никнейм:', widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.CharField(label='Email:', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label='Пароль:', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label='Повтор пароля:', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']
        labels = {
            'first_name': 'Имя:',
            'last_name': 'Фамилия:'
        }
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-input'}),
            'last_name': forms.TextInput(attrs={'class': 'form-input'})
        }

    def clean_email(self):
        cd = self.cleaned_data['email']
        if get_user_model().objects.filter(email=cd).exists():
            raise forms.ValidationError('Такой email уже существует')
        return cd


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Login', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'password']


class ProfileForm(forms.ModelForm):
    username = forms.CharField(label='Никнейм:', widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.CharField(disabled=True, label='Email:', widget=forms.TextInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name']
        labels = {
            'first_name': 'Имя:',
            'last_name': 'Фамилия:'
        }
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-input'}),
            'last_name': forms.TextInput(attrs={'class': 'form-input'})
        }


class UserChangePasswordForm(PasswordChangeForm):
    old_password = forms.CharField(label='Старый пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password1 = forms.CharField(label='Новый пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password2 = forms.CharField(label='Повтор нового пароля', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

SOUNDCLOUD/register/views.py
from django.contrib.auth import logout, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView
from .forms import *
from .utils import *


class RegisterUser(DataMixin, CreateView):
    form_class = RegisterUser
    template_name = 'register/reg.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context2 = self.get_user_context(title='Регистрация')
        return context | context2

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('main:home')


class LoginUser(DataMixin, LoginView):
    form_class = LoginUserForm
    template_name = 'register/login.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context2 = self.get_user_context(title='Войти')
        return context | context2


class Profile(DataMixin, LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = ProfileForm
    template_name = 'register/profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context2 = self.get_user_context(title='Профиль')
        return context | context2

    def get_success_url(self):
        return reverse_lazy('main:home')

    def get_object(self, queryset=None):
        return self.request.user


class UserChangePassword(PasswordChangeView):
    form_class = UserChangePasswordForm
    success_url = reverse_lazy("register:profile")
    template_name = "register/password_change_form.html"

SOUNDCLOUD/templates/register/login.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ title }}</h1>
<form method="post">
    {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">
        <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
        <p><label for="{{ f.id_for_label }}" class="form-label">{{ f.label }}</label>{{ f }}</p>
        <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <button type="submit">Войти</button>
</form>
<p><a href="{% url 'register:password_reset' %}">Забыли пароль?</a></p>
<p>Нет аккаунта? <a href="{% url 'register:reg' %}">Регистрация</a></p>
{% endblock %}

SOUNDCLOUD/templates/register/password_change_form.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ title }}</h1>
<form method="post">
    {% csrf_token %}
        <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
        <p><label for="{{ f.id_for_label }}" class="form-label">{{ f.label }}</label>{{ f }}</p>
        <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <button type="submit">Сохранить</button>
</form>

{% endblock %}

SOUNDCLOUD/templates/register/password_reset_complete.html
{% extends "admin/base_site.html" %}


{% block content %}
<h1>Пароль изменен</h1>


{% endblock %}

SOUNDCLOUD/templates/register/password_reset_confirm.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ title }}</h1>
<form method="post">
    {% csrf_token %}
        <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
        <p><label for="{{ f.id_for_label }}" class="form-label">{{ f.label }}</label>{{ f }}</p>
        <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <button type="submit">Сменить</button>
</form>

{% endblock %}

SOUNDCLOUD/templates/register/password_reset_done.html
{% extends "admin/base_site.html" %}
{% load i18n %}

{% block content %}
<h1>Сброс пароля</h1>

<p>{% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}</p>

<p>{% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}</p>

{% endblock %}

SOUNDCLOUD/templates/register/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'register:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

SOUNDCLOUD/templates/register/password_reset_form.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ title }}</h1>
<form method="post">
    {% csrf_token %}
        <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
        <p><label for="{{ f.id_for_label }}" class="form-label">{{ f.label }}</label>{{ f }}</p>
        <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <button type="submit">Отправить по Email</button>
</form>

<hr>
{% endblock %}

SOUNDCLOUD/templates/register/profile.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ title }}</h1>
<form method="post">
    {% csrf_token %}
        <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
        <p><label for="{{ f.id_for_label }}" class="form-label">{{ f.label }}</label>{{ f }}</p>
        <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <button type="submit">Сохранить</button>
</form>

<hr>
<a href="{% url 'register:password_change' %}">Сменить пароль</a>
{% endblock %}

SOUNDCLOUD/templates/register/reg.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ title }}</h1>
<form action="{% url 'register:reg' %}" method="post">
    {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">
        <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
        <p><label for="{{ f.id_for_label }}" class="form-label">{{ f.label }}</label>{{ f }}</p>
        <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <button type="submit">Зарегистрироваться</button>
</form>
{% endblock %}