SOUNDCLOUD/SOUNDCLOUD/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('register.urls')),
    path('my_audio/', include('myaudio.urls', namespace='myaudio')),
    path('', include('main.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls))
                  ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SOUNDCLOUD/main/urls.py
from django.urls import path
from .views import *

app_name = 'main'
urlpatterns = [
    path('', MusicHome.as_view(), name='home'),
    path('add/', AddMusic.as_view(), name='add'),
    path('category/<slug:cat_slug>/', ListCategories.as_view(), name='category')
]

SOUNDCLOUD/myaudio/urls.py
from django.urls import path

from .views import *
from .tasks import *

app_name = 'myaudio'
urlpatterns = [
    path('add/<int:music_id>/', music_add, name='music_add'),
    path('remove/<int:music_id>/', music_remove, name='music_remove'),
    path('my_aupiolist/', my_music_list, name='myaudiolist'),
]

SOUNDCLOUD/main/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


class Categories(models.Model):
    title = models.CharField(
        max_length=32,
        verbose_name='Название'
    )

    slug = models.SlugField(
        max_length=32,
        verbose_name='слаг',
        unique=True
    )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('main:category', kwargs={'cat_slug': self.slug})

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ['title']


class Music(models.Model):
    title = models.CharField(
        max_length=32,
        verbose_name='Название'
    )

    author = models.CharField(
        max_length=32,
        verbose_name='Автор'
    )

    slug = models.SlugField(
        max_length=32,
        verbose_name='слаг',
        unique=True,
        blank=True
    )

    image = models.ImageField(
        upload_to='photos/%Y/%m/%d',
        verbose_name='Постер',
        blank=True
    )

    soundfile = models.FileField(
        upload_to='sound/%Y/%m/%d',
        verbose_name='Трек',
        blank=True,
        db_index=True
    )

    cat = models.ForeignKey(
        Categories,
        verbose_name='Категория',
        on_delete=models.CASCADE,
        blank=True
    )

    class Meta:
        verbose_name = 'Трек'
        verbose_name_plural = 'Треки'
        ordering = ['title']

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        print('!!!------!!!!')
        super(Music, self).save(*args, **kwargs)
        if not self.slug:
            self.slug = slugify(self.title) + f'{self.author}' + f'{self.pk}'
            super().save(*args, **kwargs)

SOUNDCLOUD/main/forms.py
from django import forms
from .models import *


class AddMusicForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['cat'].empty_label = 'Категория'

    class Meta:
        model = Music
        fields = ['title', 'author', 'image', 'soundfile', 'cat']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-input'})
        }

    def clean_soundfile(self):
        work_obj = self.cleaned_data['soundfile']
        cd = str(self.cleaned_data['soundfile'])
        mp3 = cd.split('.')
        if mp3[-1] != 'mp3':
            raise forms.ValidationError('Неверный формат аудиофайла')
        else:
            return work_obj

SOUNDCLOUD/main/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView

from .models import *
from .forms import *
from .utils import *


class MusicHome(DataMixin, ListView):
    model = Music
    template_name = 'main/index.html'
    context_object_name = 'posts'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context2 = self.get_user_context(title='Главная страница')
        return context | context2


class ListCategories(DataMixin, ListView):
    model = Music
    template_name = 'main/index.html'
    context_object_name = 'posts'
    allow_empty = False

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context2 = self.get_user_context(title=context['posts'][0].cat)
        return context | context2

    def get_queryset(self):
        return Music.objects.filter(cat__slug=self.kwargs['cat_slug'])


class AddMusic(DataMixin, LoginRequiredMixin, CreateView):
    form_class = AddMusicForm
    template_name = 'main/addmusic.html'
    success_url = reverse_lazy('main:home')

    def form_valid(self, form):
        w = form.save(commit=False)
        return super(AddMusic, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context2 = self.get_user_context(title='Добавление трека')
        return context | context2

SOUNDCLOUD/templates/main/addmusic.html
{% extends 'base.html' %}

{% block content %}

<h1>{{ title }}</h1>
<form action="{% url 'main:add' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% for f in form %}
        <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
        <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <button type="submit">Добавить</button>
</form>
{% endblock %}

SOUNDCLOUD/templates/main/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
        {% for i in posts %}
        <div class="track">
            {% if i.image %}
            <span class="zapis"><img src="{{ i.image.url }}" alt="#"></span>
            {% else %}
            <span class="zapis"><img src="{% static 'img/logo.png' %}" alt="#"></span>
            {% endif %}
            <span class="zapis">
                <p>{{ i.title }}</p>
                <p>{{ i.author }}</p>
            </span>
            <span class="zapis"><p>{{ i.cat }}</p></span>
<!--            <span class="zapis"><p><audio controls><source src="{{ i.soundfile.url }}"></audio></p></span>-->
            <span class="zapis">
                <form action="{% url 'myaudio:music_add' i.id %}" method="post">
                    {% csrf_token %}
                    <input type="submit" value="Добавить себе">
                </form>
            </span>
        </div>
        {% endfor %}
{% endblock %}