SOUNDCLOUD/SOUNDCLOUD/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('register.urls')),
    path('my_audio/', include('myaudio.urls', namespace='myaudio')),
    path('', include('main.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls))
                  ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SOUNDCLOUD/main/urls.py
from django.urls import path
from .views import *

app_name = 'main'
urlpatterns = [
    path('', MusicHome.as_view(), name='home'),
    path('add/', AddMusic.as_view(), name='add'),
    path('category/<slug:cat_slug>/', ListCategories.as_view(), name='category')
]

SOUNDCLOUD/myaudio/urls.py
from django.urls import path

from .views import *
from .tasks import *

app_name = 'myaudio'
urlpatterns = [
    path('add/<int:music_id>/', music_add, name='music_add'),
    path('remove/<int:music_id>/', music_remove, name='music_remove'),
    path('my_aupiolist/', my_music_list, name='myaudiolist'),
]

SOUNDCLOUD/myaudio/models.py
from django.contrib.auth import get_user_model
from django.db import models
from main.models import Music


class MyMusic(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    music = models.ForeignKey(Music, on_delete=models.CASCADE, related_name='my_music')

    def __str__(self):
        return f'Избраное для пользователя {self.user.username}'

SOUNDCLOUD/myaudio/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST
from django.views.generic import ListView

from .models import *
from .utils import *


# class MyAudioList(DataMixin, ListView):
#     model = MyMusic
#     template_name = 'myaudio/myaudio.html'
#     context_object_name = 'myaudio'
#
#     def get_context_data(self, *, object_list=None, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context2 = self.get_user_context(title="Мои аудиозаписи")
#         return context | context2

@login_required
def my_music_list(request):
    my_music = MyMusic.objects.filter(user=request.user)
    menu = [
        {'title': 'Главная страница', 'url_name': 'main:home'},
        {'title': 'Добавить трек', 'url_name': 'main:add'}
    ]
    cats = Categories.objects.all()
    context = {'my_music': my_music,
               'menu': menu,
               'cats': cats,
               'title': "Мои аудиозаписи"
               }
    return render(request, 'myaudio/myaudio.html', context)

SOUNDCLOUD/templates/myaudio/myaudio.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% for i in my_music %}
        <div class="track">
            {% if i.music.image %}
            <span class="zapis"><img src="{{ i.music.image.url }}" alt="#"></span>
            {% else %}
            <span class="zapis"><img src="{% static 'img/logo.png' %}" alt="#"></span>
            {% endif %}
            <span class="zapis">
                <p>{{ i.music.title }}</p>
                <p>{{ i.music.author }}</p>
            </span>
            <span class="zapis"><p>{{ i.music.release }}</p></span>
            <span class="zapis"><p>{{ i.music.cat }}</p></span>
<!--            <span class="zapis"><p><audio controls ><source src="{{ i.music.soundfile.url }}"></audio></p></span>-->
            <span class="zapis">
                <form action="{% url 'myaudio:music_remove' i.music.id %}" method="post">
                    {% csrf_token %}
                    <input type="submit" value="Удалить">
                </form>
            </span>
        </div>
        {% endfor %}
{% endblock %}