SOUNDCLOUD/SOUNDCLOUD/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('register.urls')),
    path('my_audio/', include('myaudio.urls', namespace='myaudio')),
    path('', include('main.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls))
                  ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SOUNDCLOUD/main/urls.py
from django.urls import path
from .views import *

app_name = 'main'
urlpatterns = [
    path('', MusicHome.as_view(), name='home'),
    path('add/', AddMusic.as_view(), name='add'),
    path('category/<slug:cat_slug>/', ListCategories.as_view(), name='category')
]

SOUNDCLOUD/myaudio/urls.py
from django.urls import path

from .views import *
from .tasks import *

app_name = 'myaudio'
urlpatterns = [
    path('add/<int:music_id>/', music_add, name='music_add'),
    path('remove/<int:music_id>/', music_remove, name='music_remove'),
    path('my_aupiolist/', my_music_list, name='myaudiolist'),
]

SOUNDCLOUD/register/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, \
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path
from .views import *

app_name = 'register'
urlpatterns = [
    path('', LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password-change/', UserChangePassword.as_view(), name='password_change'),
    path('password-reset/', PasswordResetView.as_view(
        template_name='register/password_reset_form.html',
        email_template_name='register/password_reset_email.html',
        success_url=reverse_lazy('register:password_reset_done')),
         name='password_reset'),
    path('password-reset-done/', PasswordResetDoneView.as_view(
        template_name='register/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='register/password_reset_confirm.html',
        success_url=reverse_lazy('register:login')),
         name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(
        template_name='register/password_reset_complete.html'),
         name='password_reset_complete'),
    path('register/', RegisterUser.as_view(), name='reg'),
    path('profile/', Profile.as_view(), name='profile'),
]

SOUNDCLOUD/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="shortcut icon" href="{% static 'img/icon.png' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <script>
        let audioNL = document.querySelectorAll('audio');
        let audio = Array.apply(null, audioNL);

        audio.forEach(t => {
            let index = audio.indexOf(t);

            t.addEventListener('play', ()=> {
                audio.forEach(subT => {
                    subT !== audio[index] ?
                    (subT.pause(), subT.currentTime = 0) :
                    subT.play()
                })
            })
            t.addEventListener('ended', ()=> {
                t.currentTime = 0;
                index !== audio.length - 1 ?
                    audio[index + 1].play() :
                    null
            })
        });
    </script>
</head>
<body>
{% block header %}
<header>
    <div class="left-menu">
        <span><a href="{% url 'main:home' %}"><img src="{% static 'img/logo.png' %}" alt="logo"></a></span>
        {% for i in menu %}
        <span style="margin-left: 30px;"><a href="{% url i.url_name %}">{{ i.title }}</a></span>
        {% endfor %}
        {% if request.user.is_authenticated %}
        <span style="margin-left: 30px;"><a href="{% url 'myaudio:myaudiolist' %}">Мои аудио</a></span>
        {% endif %}
    </div>
    <div class="right-menu">
        {% if request.user.is_authenticated %}
        <span><a href="{% url 'register:profile' %}">{{ user.username }}</a> | <a href="{% url 'register:logout' %}">Выйти</a></span>
        {% else %}
        <span><a href="{% url 'register:login' %}">Войти</a></span>
        {% endif %}
    </div>
</header>
{% endblock %}

{% block aside %}
<aside>
    <ul>
        <li><a href="{% url 'main:home' %}">Все категории</a></li>
        {% for i in cats %}
            <li><a href="{{ i.get_absolute_url }}">{{ i.title }}</a></li>
        {% endfor %}
    </ul>
</aside>
{% endblock %}
{% block content %}
{% endblock %}
{% if page_obj.has_other_pages %}
<nav class="list-pages">
    {% if page_obj.has_previous %}
    <li class="page-num"><a href="?page={{ page_obj.previous_page_number }}">&lt;</a></li>
    {% endif %}
    <ul>
    {% for p in paginator.page_range %}
        {% if page_obj.number == p %}
        <li class="page-num page-num-selected">{{ p }}</li>
        {% elif p >= page_obj.number|add:-1 and p <= page_obj.number|add:1 %}
        <li class="page-num"><a href="?page={{ p }}">{{ p }}</a></li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
    <li class="page-num"><a href="?page={{ page_obj.next_page_number }}">&gt;</a></li>
    {% endif %}
    </ul>
</nav>
{% endif %}
</body>
</html>